package vo;
// Generated 07/12/2017 22:43:57 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TbCliente generated by hbm2java
 */
public class TbCliente  implements java.io.Serializable {


     private Integer idCliente;
     private String nome;
     private String email;
     private Long telefone;
     private Double cpf;
     private String sexo;
     private Date datanascimento;

    public TbCliente() {
    }

	
    public TbCliente(String nome) {
        this.nome = nome;
    }
    public TbCliente(String nome, String email, Long telefone, Double cpf, String sexo, Date datanascimento) {
       this.nome = nome;
       this.email = email;
       this.telefone = telefone;
       this.cpf = cpf;
       this.sexo = sexo;
       this.datanascimento = datanascimento;
    }
   
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Long getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(Long telefone) {
        this.telefone = telefone;
    }
    public Double getCpf() {
        return this.cpf;
    }
    
    public void setCpf(Double cpf) {
        this.cpf = cpf;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public Date getDatanascimento() {
        return this.datanascimento;
    }
    
    public void setDatanascimento(Date datanascimento) {
        this.datanascimento = datanascimento;
    }




}


